projetmvcfinale/Models/Corrige.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace projetmvcfinale.Models
{
    public partial class Corrige
    {
        public Corrige()
        {
            Exercice = new HashSet<Exercice>();
        }
        [Display(Name = "Numéro de corrigé")]
        public int Idcorrige { get; set; }
        [Display(Name = "Titre")]
        [Required]
        public string CorrigeDocNom { get; set; }
        [Required]
        public string Lien { get; set; }
        [Display(Name = "Date d'insertion")]
        public DateTime DateInsertion { get; set; }
        [Display(Name = "Exercice associé")]
        public int Idexercice { get; set; }

        [Display(Name = "Exercice associé")]
        public Exercice IdexerciceNavigation { get; set; }
        public ICollection<Exercice> Exercice { get; set; }
    }
}

projetmvcfinale/Models/CorrigeViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace projetmvcfinale.Models
{
    public class CorrigeViewModel
    {
        public int idcorrige { get; set; }
        [Display(Name ="Titre")]
        [Required (ErrorMessage="Champs obligatoire")]
        public string CorrigeDocNom { get; set; }
        public IFormFile Lien { get; set; }
        [Display(Name = "Exercice associé")]
        [Required(ErrorMessage = "Champs obligatoire")]
        public int Idexercice { get; set; }
    }
}

projetmvcfinale/Controllers/CorrigeController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using projetmvcfinale.Models;

namespace projetmvcfinale.Controllers
{
    public class CorrigeController : Controller
    {
        private readonly ProjetFrancaisContext provider;
        private readonly IConfiguration Configuration;
        public string ConnectionString;
        private SqlConnection sqlConnection;
        private List<Corrige> listeCor;

        //Controlleur
        public CorrigeController(IConfiguration configuration)
        {
            this.Configuration = configuration;
            this.provider = new ProjetFrancaisContext(this.Configuration.GetConnectionString("DefaultConnection"));
            this.ConnectionString = Configuration.GetConnectionString("DefaultConnection");
            this.sqlConnection = new SqlConnection(this.ConnectionString);
            this.listeCor = this.provider.Corrige.ToList();
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            //Pour permettre au ViewBag contenantn les categores d'etre accessible en tout temps    
            base.OnActionExecuted(context);
            ViewBag.Categories = this.provider.Categorie.ToList();
            ViewBag.Notes = this.provider.NoteDeCours.ToList();
            ViewBag.NiveauDif = this.provider.Niveau.ToList();
            ViewBag.souscatégorie = this.provider.SousCategorie.ToList();
            //Merci https://stackoverflow.com/questions/40330391/set-viewbag-property-in-the-constructor-of-a-asp-net-mvc-core-controller
        }
        public IActionResult ListeCorrige(string search)
        {
            //Retourne la liste des corrigés
            return View(this.provider.Corrige.Where(x => x.CorrigeDocNom.StartsWith(search) || search == null).ToList());
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AjouterCorrige()
        {
            //Retourne le selectList de tout les exercices
            ViewBag.Idexercice = new SelectList(this.provider.Exercice, "Idexercice", "NomExercices");
            //Retourne la vue pour ajouter un corrigé
            return View();
        }
        /// <summary>
        /// Ajouter un corrigé dans la bd
        /// </summary>
        /// <param name="corrige"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AjouterCorrige([Bind("CorrigeDocNom,Lien,Idexercice")] CorrigeViewModel corrigeVM)
        {
            try
            {
                //Boolean regardant s'il s'agit d'un exercice pdf ou word
                bool pdfOuWord = true;
                //Vérifie si un lien a été ajouté
                if (corrigeVM.Lien != null)
                {
                    if (ModelState.IsValid)
                    {
                        pdfOuWord = false;
                        //Voir si le document est un pdf ou word
                        Regex reg = new Regex("\\.pdf$|\\.docx$|\\.doc$");
                        Match match = reg.Match(corrigeVM.Lien.FileName);
                        if (match.Success)
                        {
                            //Laisse savoir qu'il s'agit d'un pdf ou word
                            pdfOuWord = true;
                        }
                        //s'il s'agit d'un pdf ou word
                        if (pdfOuWord == true)
                        {
                            //conversion du ViewModel en corrigé
                            Corrige corrige = new Corrige()
                            {
                                CorrigeDocNom = corrigeVM.CorrigeDocNom,
                                Lien = corrigeVM.Lien.FileName,
                                DateInsertion = DateTime.Now,
                                Idexercice = corrigeVM.Idexercice
                            };
                            //ajoute le corrige
                            provider.Add(corrige);
                            await provider.SaveChangesAsync();
                            //associer
                            Exercice ex = this.provider.Exercice.ToList().Find(x => x.Idexercice == corrige.Idexercice);
                            ex.Idcorrige = corrige.Idcorrige;
                            provider.Exercice.Update(ex);
                            await provider.SaveChangesAsync();
                            //Insérer dans la BD le document     
                            var chemin = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\Corrige", corrige.Lien);
                            //Prendre la find du doc(.pdf / .doc / docx)
                            string format = corrige.Lien.Substring(corrige.Lien.Length - 4);
                            if (format == "docx")
                            {
                                format = ".docx";
                            }
                            //https://stackoverflow.com/questions/6413572/how-do-i-get-the-last-four-characters-from-a-string-in-c
                            using (var stream = new FileStream(chemin, FileMode.Create))
                            {
                                await corrigeVM.Lien.CopyToAsync(stream);
                            }
                            //Change le nom du document
                            System.IO.File.Move(chemin, Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\Corrige", corrige.Idcorrige.ToString() + format));
                            //ajouter le lien à la base de données
                            corrige.Lien = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\NoteDeCours", corrige.Idcorrige.ToString() + format);
                            await provider.SaveChangesAsync();

                            return RedirectToAction(nameof(ListeCorrige));
                        }
                        //S'il ne s'agit aps de pdf ou word, retourner la view d'ajout
                        ViewBag.pdf_Word = "Avertissement";
                    }
                }
                //Si aucun lien n'a été rajouté, retourner la vue d'ajout et ne pas accepter la requete
                ViewBag.pdf_Word2 = "Avertissement";
                ViewBag.Idexercice = new SelectList(this.provider.Exercice, "Idexercice", "NomExercices");
                return View("AjouterCorrige");
            }
            catch (Exception e)
            {
                return View("\\Views\\Shared\\page_erreur.cshtml");
            }
        }

        /// <summary>
        /// Afficher la vue pour modifier un corrige
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<ActionResult> ModifierCorrige(int id)
        {
            try
            {
                //Si le id n est pas valide
                if (id.ToString() == null)
                    return View("\\Views\\Shared\\page_erreur.cshtml");
                //Trouver le corrigé associé
                Corrige cr = await provider.Corrige.FindAsync(id);
                //Si le corrigé n'existe pas
                if (cr == null)
                    return View("\\Views\\Shared\\page_erreur.cshtml");
                //transfer en ViewModel
                CorrigeViewModel corrige = new CorrigeViewModel()
                {
                    idcorrige = cr.Idcorrige,
                    CorrigeDocNom = cr.CorrigeDocNom,
                };
                //lien du document
                this.HttpContext.Session.SetString("Lien", cr.Lien);
                //liste d'exercice existant
                ViewBag.Idexercice = new SelectList(this.provider.Exercice, "Idexercice", "NomExercices");

                return View(corrige);
            }
            catch (Exception e)
            {
                return View("\\Views\\Shared\\page_erreur.cshtml");
            }

        }
        /// <summary>
        /// Modifier un corrigé existant
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> ModifierCorrige(CorrigeViewModel corrigeVM)
        {
            if (ModelState.IsValid)
            {
                //Si le corrigeVM n'est pas valide
                if (corrigeVM == null)
                    return NotFound();
                //Trouver le corrigé associé
                Corrige cr = await provider.Corrige.FindAsync(corrigeVM.idcorrige);
                //Mettre a jour ses variables envoyés
                cr.CorrigeDocNom = corrigeVM.CorrigeDocNom;
                cr.Idexercice = corrigeVM.Idexercice;

                //vérifier si le lien est existant ou non
                if (corrigeVM.Lien != null)
                {
                    cr.Lien = corrigeVM.Lien.FileName;

                    //changer le document associé
                    if (corrigeVM.Lien != null || corrigeVM.Lien.Length != 0)
                    {
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\Corrige", this.HttpContext.Session.GetString("Lien"));
                        string vieuxChemin = path;
                        //supprimer le vieux document
                        if (System.IO.File.Exists(vieuxChemin))
                        {
                            System.IO.File.Delete(vieuxChemin);

projetmvcfinale/Views/Corrige/AjouterCorrige.cshtml
@model projetmvcfinale.Models.CorrigeViewModel

@{
    ViewData["Title"] = "AjouterCorrige";
}

<h1>Ajouter un corrigé</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AjouterCorrige" asp-controller="Corrige" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CorrigeDocNom" class="control-label"></label>
                <input asp-for="CorrigeDocNom" class="form-control" />
                <span asp-validation-for="CorrigeDocNom" class="text-danger"></span>
            </div>
            @if (((ViewBag.Idexercice) as SelectList).Count() == 0)
            {
                <p style="color:red">Créez des exercices avant d'insérer des corrigés!</p>
            }
            <div class="form-group">
                <label asp-for="Idexercice" class="control-label"></label>
                <select asp-for="Idexercice" class="form-control" asp-items="ViewBag.Idexercice"></select>
            </div>
            @if (ViewBag.pdf_Word == "Avertissement")
            {
                <p style="color:red">Le document doit être un pdf ou word!</p>
            }
            else if (ViewBag.pdf_Word2 == "Avertissement")
            {
                <p style="color:red">Vous devez insérer un document! (pdf ou word)</p>
            }
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                <input asp-for="Lien" class="form-control" type="file" />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter ce corrigé" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="ListeCorrige" class="btn btn-info">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

projetmvcfinale/Views/Corrige/ListeCorrige.cshtml
@model IEnumerable<projetmvcfinale.Models.Corrige>

@{
    ViewData["Title"] = "ListeCorrige";
}

<h2><u>Liste des corrigés disponibles</u></h2><br />
@if (User.IsInRole("Admin"))
{
<p>
    <a asp-action="AjouterCorrige" class=" btn btn-info">Ajouter un corrigé</a>
</p>
}


<table class="table table-responsive table-hover table-condensed" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CorrigeDocNom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateInsertion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdexerciceNavigation.NomExercices)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CorrigeDocNom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateInsertion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idexercice)
                </td>
                <td>
                    @if (item.Lien != null)
                    {
                        <a class="btn btn-info" href="../Documents/Corrige/@item.Lien.Split('\\').Last()"><i class="fas fa-file-pdf iconlist"></i>Afficher</a>
                    }
                    else
                    {
                        <a class="btn btn-info testing" href="#"><i class="fas fa-file-pdf iconlist"></i> Afficher<span>Lien manquant</span></a>
                    }
                    
                    @if (User.IsInRole("Admin"))
                    {                     
                    <a class="btn btn-info" style="background-color:#863e94" asp-action="ModifierCorrige" asp-route-id="@item.Idcorrige"><i class="fas fa-edit"></i> Modifier</a>
                    <a class="btn btn-info" style="background-color:#e03689" asp-action="SupprimerCorrige" asp-route-id="@item.Idcorrige"><i class="fas fa-trash-alt"></i> Supprimer</a>
                    }
                    
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/1.10.19/i18n/French.json"></script>


    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: {
                    processing: "Traitement en cours...",
                    search: "Rechercher&nbsp;:",
                    lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                    info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix: "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable: "Aucune donnée disponible dans le tableau",
                    paginate: {
                        first: "Premier",
                        previous: "Pr&eacute;c&eacute;dent",
                        next: "Suivant",
                        last: "Dernier"
                    },
                    aria: {
                        sortAscending: ": activer pour trier la colonne par ordre croissant",
                        sortDescending: ": activer pour trier la colonne par ordre décroissant"
                    }
                }
            });

            $("input[type='search']").css({ "border-radius": "10px", "border": "2px solid #17a2b8" });

        });
    </script>

}

projetmvcfinale/Views/Corrige/ModifierCorrige.cshtml
@model projetmvcfinale.Models.CorrigeViewModel

@{
    ViewData["Title"] = "ModifierCorrige";
}

<h2>Modifier un corrigé</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ModifierCorrige" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idcorrige" />
            <div class="form-group">
                <label asp-for="CorrigeDocNom" class="control-label"></label>
                <input asp-for="CorrigeDocNom" class="form-control" />
                <span asp-validation-for="CorrigeDocNom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                <input asp-for="Lien" class="form-control" type="file"  />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idexercice" class="control-label"></label>
                <select asp-for="Idexercice" class="form-control" asp-items="ViewBag.Idexercice"></select>
                <span asp-validation-for="Idexercice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListeCorrige" class="btn btn-info">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

projetmvcfinale/Views/Corrige/SupprimerCorrige.cshtml
@model projetmvcfinale.Models.Corrige

@{
    ViewData["Title"] = "SupprimerCorrige";
}

<h2>Supprimer un corrigé</h2>
<div>
    <h4>Corrigé</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CorrigeDocNom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CorrigeDocNom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateInsertion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateInsertion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdexerciceNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdexerciceNavigation.AdresseCourriel)
        </dd>
    </dl>
    
    <form asp-action="SupprimerCorrigePost" asp-controller="Corrige" asp-route-id="@Model.Idcorrige">
        <input type="submit" value="Supprimer" class="btn btn-info" /> |
        <a asp-action="ListeCorrige" class="btn btn-info">Retour à la liste</a>
    </form>
</div>

projetmvcfinale/Views/Corrige/UploadCorrige.cshtml
@model projetmvcfinale.Models.Corrige

<h4>Ajouter le fichier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="Corrige" asp-action="UploadCorrige">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                <input asp-for="Lien" class="form-control" type="file" />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Téléverser" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListeCorrige" class="btn btn-primary">Retour à la liste</a>
</div>