projetmvcfinale/Models/NoteDeCours.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace projetmvcfinale.Models
{
    public partial class NoteDeCours
    {
        public NoteDeCours()
        {
            Exercice = new HashSet<Exercice>();
        }
        [Display(Name = "Numéro")]
        public int IdDocument { get; set; }
        [Display(Name = "Titre du document")]
        [Required(ErrorMessage ="Ce champs est nécessaire")]
        public string NomNote { get; set; }
        public string Lien { get; set; }
        [Display(Name = "Date d'insertion")]
        public DateTime DateInsertion { get; set; }
        [Display(Name = "Adresse Courriel")]
        public string AdresseCourriel { get; set; }
        [Display(Name = "Catégorie")]
        [Required]
        public int IdCateg { get; set; }
        [Display(Name = "Sous-catégorie")]
        [Required]
        public int IdSousCategorie { get; set; }

        public Utilisateur AdresseCourrielNavigation { get; set; }
        public Categorie IdCategNavigation { get; set; }
        public SousCategorie IdSousCategorieNavigation { get; set; }
        public ICollection<Exercice> Exercice { get; set; }
    }
}

projetmvcfinale/Controllers/NoteDeCoursController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using projetmvcfinale.Models;

namespace projetmvcfinale.Controllers
{
    public class NoteDeCoursController : Controller
    {
        private readonly ProjetFrancaisContext provider;
        private readonly IConfiguration Configuration;
        public string ConnectionString;
        private SqlConnection sqlConnection;

        public NoteDeCoursController(IConfiguration configuration)
        {
            this.Configuration = configuration;
            this.provider = new ProjetFrancaisContext(this.Configuration.GetConnectionString("DefaultConnection"));
            this.ConnectionString = Configuration.GetConnectionString("DefaultConnection");
            this.sqlConnection = new SqlConnection(this.ConnectionString);
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            //Pour permettre au ViewBag contenantn les categores d'etre accessible en tout temps    
            base.OnActionExecuted(context);
            ViewBag.Categories = this.provider.Categorie.ToList();
            ViewBag.Notes = this.provider.NoteDeCours.ToList();
            ViewBag.NiveauDif = this.provider.Niveau.ToList();
            ViewBag.souscatégorie = this.provider.SousCategorie.ToList();
            //Merci https://stackoverflow.com/questions/40330391/set-viewbag-property-in-the-constructor-of-a-asp-net-mvc-core-controller
        }

        public IActionResult ListeNoteDeCours(string search)
        {
            return View(this.provider.NoteDeCours.Where(x => x.IdSousCategorieNavigation.NomSousCategorie.StartsWith(search) || x.IdCategNavigation.NomCategorie.StartsWith(search) || search == null).ToList());
        }
        /// <summary>
        /// Afficher la vue pour ajouter une note
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AjouterNote()
        {
            ViewBag.IdCateg = new SelectList(this.provider.Categorie.ToList(), "IdCateg", "NomCategorie");
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="note"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AjouterNote([Bind("NomNote,IdCateg,SousCategorie,Lien")] NotesViewModel noteVM)//
        {
            try
            {
                bool pfdOuWord = true;
                bool lienAjoute = true;

                if (ModelState.IsValid)
                {
                    if (noteVM.Lien == null)
                    {
                        lienAjoute = false;
                    }
                    else
                    {
                        pfdOuWord = false;
                        //Voir si le document est un pdf ou word
                        Regex reg = new Regex("\\.pdf$|\\.docx$|\\.doc$");
                        Match match = reg.Match(noteVM.Lien.FileName);
                        if (match.Success)
                        {
                            pfdOuWord = true;
                        }
                    }

                    if (pfdOuWord == true)
                    {
                        //Transferer en note
                        NoteDeCours note;
                        //Voir s'il y a un lien ou non qui a été envoyé
                        if (noteVM.Lien != null)
                        {
                            note = new NoteDeCours()
                            {
                                NomNote = noteVM.NomNote,
                                IdCateg = noteVM.IdCateg,
                                IdSousCategorie = this.provider.SousCategorie.ToList().Find(x => x.NomSousCategorie == noteVM.SousCategorie).IdSousCategorie,
                                Lien = noteVM.Lien.FileName,
                                AdresseCourriel = this.HttpContext.User.Identity.Name,
                                DateInsertion = DateTime.Now

                            };
                        }
                        else
                        {
                            note = new NoteDeCours()
                            {
                                NomNote = noteVM.NomNote,
                                IdCateg = noteVM.IdCateg,
                                IdSousCategorie = this.provider.SousCategorie.ToList().Find(x => x.NomSousCategorie == noteVM.SousCategorie).IdSousCategorie,
                                AdresseCourriel = this.HttpContext.User.Identity.Name,
                                Lien = "",
                                DateInsertion = DateTime.Now

                            };
                        }
                        provider.Add(note);
                        await provider.SaveChangesAsync();
                        //HttpContext.Session.SetString("NoteDeCours", JsonConvert.SerializeObject(note));//pour aller le chercher pour l'upload
                        //Insérer dans la BD le document
                        if (lienAjoute == true)
                        {
                            var chemin = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\NoteDeCours", note.Lien);
                            //Prendre la find du doc(.pdf / .doc / docx)
                            string format = note.Lien.Substring(note.Lien.Length - 4);
                            if (format == "docx")
                            {
                                format = ".docx";
                            }
                            //https://stackoverflow.com/questions/6413572/how-do-i-get-the-last-four-characters-from-a-string-in-c
                            using (var stream = new FileStream(chemin, FileMode.Create))
                            {
                                await noteVM.Lien.CopyToAsync(stream);
                            }
                            //Change le nom du document
                            System.IO.File.Move(chemin, Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\NoteDeCours", note.IdDocument.ToString() + format));
                            //ajouter le lien à la base de données
                            note.Lien = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Documents\\NoteDeCours", note.IdDocument.ToString() + format);
                            await provider.SaveChangesAsync();
                        }
                        return RedirectToAction(nameof(ListeNoteDeCours));
                    }
                    ViewBag.pdf_Word = "Avertissement";

                }
                //Retour de la page en cas d'erreur
                ViewBag.IdCateg = new SelectList(this.provider.Categorie.ToList(), "IdCateg", "NomCategorie");
                return View(noteVM);
            }
            catch (Exception e)
            {
                return View("\\Views\\Shared\\page_erreur.cshtml");
            }
        }

        /// <summary>
        /// Modifier une note éxistante
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult ModifierNote(int id)
        {
            try
            {
                //Retirer les bonnes notes de cours
                NoteDeCours noteDeCours = this.provider.NoteDeCours.ToList().Find(x => x.IdDocument == id);
                //Version view Model
                NotesViewModel noteVM = new NotesViewModel()
                {
                    NomNote = noteDeCours.NomNote,
                    IdCateg = noteDeCours.IdCateg,
                    SousCategorie = this.provider.SousCategorie.ToList().Find(x => x.IdSousCategorie == noteDeCours.IdSousCategorie).NomSousCategorie
                };
                //Insérer le ID dans une session
                this.HttpContext.Session.SetString("IdNotes", id.ToString());
                //Le lien actuel dans une session egalement
                this.HttpContext.Session.SetString("Link", noteDeCours.Lien);
                this.HttpContext.Session.SetString("Lien", JsonConvert.SerializeObject(noteDeCours.Lien));
                //Viewbag contenant le lien du document
                ViewBag.Link = noteDeCours.Lien;
                //Retourenr la vue permettant de modifier
                ViewBag.IdCateg = new SelectList(this.provider.Categorie.ToList(), "IdCateg", "NomCategorie");
                this.HttpContext.Session.SetString("noteVm", JsonConvert.SerializeObject(noteVM));
                return View(noteVM);
            }
            catch (Exception e)
            {
                return View("\\Views\\Shared\\page_erreur.cshtml");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ModifierNote(NotesViewModel noteVM)
        {
            try
            {
                bool changement = true;
                bool pfdOuWord = false;
                //Récupréer le lien si aucun lien n'a été indiqué
                if (noteVM.Lien == null)
                {
                    changement = false;
                }
                if (ModelState.IsValid)
                {
                    if (changement == true)
                    {
                        //Voir si le document est un pdf ou word
                        Regex reg = new Regex("\\.pdf$|\\.docx$|\\.doc$");
                        Match match = reg.Match(noteVM.Lien.FileName);

projetmvcfinale/Views/NoteDeCours/AjouterNote.cshtml
@model projetmvcfinale.Models.NotesViewModel

@{
    ViewData["Title"] = "AjouterNote";
}
<br />
<p>
    <button class="btn btn-info" data-toggle="modal" data-target="#ModalAjouterSousCategorie">Ajouter une sous-catégorie</button>
</p>

<h2>Ajouter des Note</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AjouterNote" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomNote" class="control-label"></label>
                <input asp-for="NomNote" class="form-control" />
                <span asp-validation-for="NomNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCateg" class="control-label"></label>
                <select asp-for="IdCateg" class="form-control" asp-items="ViewBag.IdCateg"></select>
            </div>
            <div class="form-group">
                <label asp-for="SousCategorie" class="control-label"></label>
                <select asp-for="SousCategorie" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                @if (ViewBag.pdf_Word == "Avertissement")
                {
                    <h1 style="color:red;">document pdf ou word SEULEMENT!</h1>
                }
                <input asp-for="Lien" class="form-control" type="file" />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter ce cour" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListeNoteDeCours" class="btn btn-primary">Retour à la liste</a>
</div>

<!-- Modal -->
<div class="modal fade" id="ModalAjouterSousCategorie" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ajouter une sous-catégorie</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Nom de la sous-catégorie</label>
                <input id="NomSousCategorie" />
                <br />
                <label style="font-size: 16px;color: black;">Catégorie associée</label>
                <input id="CategorieAssociee" readonly />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="CreerSousCategorieAjax()" data-dismiss="modal">Ajouter cette catégorie</button>
                <button type="button" class="btn btn-primary" onclick="AnnulerAjouterSousCategorie()">Annuler</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/js/Notes.js"></script>
}

projetmvcfinale/Views/NoteDeCours/Index.cshtml
@model IEnumerable<projetmvcfinale.Models.NoteDeCours>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomNote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateInsertion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdresseCourrielNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCategNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSousCategorieNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomNote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateInsertion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdresseCourrielNavigation.AdresseCourriel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCategNavigation.NomCategorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSousCategorieNavigation.NomSousCategorie)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdDocument">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdDocument">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdDocument">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

projetmvcfinale/Views/NoteDeCours/ListeNoteDeCours.cshtml
@model IEnumerable<projetmvcfinale.Models.NoteDeCours>

@{
    ViewData["Title"] = "Index";
}

<h2><u>Liste des notes de cours disponibles</u></h2><br />
@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="AjouterNote" class="btn btn-info">Ajouter des notes de cours</a>
    </p>
}


<table class="table table-responsive table-hover table-condensed" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomNote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdresseCourriel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateInsertion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCategNavigation.NomCategorie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSousCategorieNavigation.NomSousCategorie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomNote)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdresseCourriel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateInsertion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCategNavigation.NomCategorie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSousCategorieNavigation.NomSousCategorie)
                </td>
                <td>
                    @if (item.Lien != "")
                    {
                        <a class="btn btn-info" href="../Documents/NoteDeCours/@item.Lien.Split('\\').Last()"><i class="fas fa-file-pdf"></i> Afficher le cour</a>
                    }
                    else
                    {
                        <a class="btn btn-info testing" href="#"><i class="fas fa-file-pdf"></i>Afficher le cour<span>Lien manquant</span></a>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="btn btn-info" style="background-color:#863e94" asp-action="ModifierNote" asp-route-id="@item.IdDocument"><i class="fas fa-edit"></i> Modifier</a>
                        <a class="btn btn-info" style="background-color:#e03689" asp-action="SupprimerNote" asp-route-id="@item.IdDocument"><i class="fas fa-trash-alt"></i> Supprimer</a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/1.10.19/i18n/French.json"></script>


    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                language: {
                    processing: "Traitement en cours...",
                    search: "Rechercher&nbsp;:",
                    lengthMenu: "Afficher _MENU_ &eacute;l&eacute;ments",
                    info: "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                    infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                    infoFiltered: "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix: "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable: "Aucune donnée disponible dans le tableau",
                    paginate: {
                        first: "Premier",
                        previous: "Pr&eacute;c&eacute;dent",
                        next: "Suivant",
                        last: "Dernier"
                    },
                    aria: {
                        sortAscending: ": activer pour trier la colonne par ordre croissant",
                        sortDescending: ": activer pour trier la colonne par ordre décroissant"
                    }
                }
            });

            $("input[type='search']").css({ "border-radius": "10px", "border": "2px solid #17a2b8" });

        });
    </script>

}

projetmvcfinale/Views/NoteDeCours/ModifierNote.cshtml
@model projetmvcfinale.Models.NotesViewModel

@{
    ViewData["Title"] = "ModifierNote";
}

<h2>ModifierNote</h2>

<h4>NoteDeCours</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ModifierNote" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomNote" class="control-label"></label>
                <input asp-for="NomNote" class="form-control" />
                <span asp-validation-for="NomNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCateg" class="control-label"></label>
                <select asp-for="IdCateg" class="form-control" asp-items="ViewBag.IdCateg"></select>
                <span asp-validation-for="IdCateg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SousCategorie" class="control-label"></label>
                <select asp-for="SousCategorie" class="form-control"></select>
                <span asp-validation-for="SousCategorie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                <input asp-for="Lien" value="@ViewBag.Link" class="form-control" type="file" />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            @if (ViewBag.pdf_Word == "Avertissement")
            {
                <h1 style="color:red;">document pdf ou word SEULEMENT!</h1>
            }
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListeNoteDeCours" class="btn btn-info">Annuler les modifications</a>
</div>

@section Scripts {
    <script src="~/js/Notes.js"></script>
}

projetmvcfinale/Views/NoteDeCours/SupprimerNote.cshtml
@model projetmvcfinale.Models.NotesViewModel

@{
    ViewData["Title"] = "SupprimerNote";
}

<h2>Supprimer un énoncé de note</h2>

<div>
    <h4>NotesViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomNote)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomNote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCateg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCateg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SousCategorie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SousCategorie)
        </dd>
    </dl>
    
    <form asp-action="SupprimerNote">
        <input type="submit" value="Supprimer" class="btn btn-info" /> |
        <a asp-action="ListeNoteDeCours" class="btn btn-info">Annuler</a>
    </form>
</div>

projetmvcfinale/Views/NoteDeCours/UploadNote.cshtml
@model projetmvcfinale.Models.NoteDeCours

<h4>Ajouter un fichier de note de cours</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UploadNote" enctype="multipart/form-data" method="post" asp-controller="NoteDeCours" asp-action="UploadNote">
            <div class="form-group">
                <label asp-for="Lien" class="control-label"></label>
                <input asp-for="Lien" class="form-control" type="file" />
                <span asp-validation-for="Lien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Téléverser" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="ListeNoteDeCours" class="btn btn-primary">Retour à la liste</a>
</div>

projetmvcfinale/Views/NoteDeCours/creerpdf.cshtml
@{
    ViewData["Title"] = "creerpdf";
}

<h4 style="margin-top:10px"><u>Créer un document pdf</u></h4>

<hr />
<textarea name="editor1" id="editor1" rows="10" cols="80">
                This is my textarea to be replaced with CKEditor.
</textarea>



@section Scripts{
    
<script src="//cdn.ckeditor.com/4.11.1/full/ckeditor.js"></script>
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor1');
    </script>
}